name = breakdance_npc
description = Spanish breakdancer NPCs that dance when a ve_radio:radio or djdeck blocks are nearby
author = ronrob-lu
version = 1.0
depends = 
optional_depends = ve_radio, djdeck
